# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Sep 28 18:04:02 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(370, 520)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CMD GPS Data Calibration", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setWindowIcon(QtGui.QIcon('/Py/includes/icon.PNG'))      
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.open_data_pushButton = QtGui.QPushButton(self.centralwidget)
        self.open_data_pushButton.setGeometry(QtCore.QRect(10, 0, 111, 23))
        self.open_data_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the CMD data File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_data_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Data File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_data_pushButton.setObjectName(_fromUtf8("open_data_pushButton"))
        self.data_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.data_lineEdit.setGeometry(QtCore.QRect(130, 0, 231, 20))
        self.data_lineEdit.setObjectName(_fromUtf8("data_lineEdit"))
        self.open_calb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.open_calb_pushButton.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.open_calb_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the CMD data calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibration File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb_pushButton.setObjectName(_fromUtf8("open_calb_pushButton"))
        self.calb_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.calb_lineEdit.setGeometry(QtCore.QRect(130, 30, 231, 20))
        self.calb_lineEdit.setObjectName(_fromUtf8("calb_lineEdit"))   
        self.calb_lineEdit.setPlaceholderText("I am going to do something here")
        self.Output_dir_pushButton = QtGui.QPushButton(self.centralwidget)
        self.Output_dir_pushButton.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.Output_dir_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a different output directory if required", None, QtGui.QApplication.UnicodeUTF8))
        self.Output_dir_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.Output_dir_pushButton.setObjectName(_fromUtf8("Output_dir_pushButton"))
        self.output_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.output_lineEdit.setGeometry(QtCore.QRect(130, 60, 231, 20))
        self.output_lineEdit.setObjectName(_fromUtf8("output_lineEdit"))
        
        self.calb_int = QtGui.QGroupBox(self.centralwidget)
        self.calb_int.setGeometry(QtCore.QRect(10, 90, 161, 56))
        self.calb_int.setTitle(QtGui.QApplication.translate("MainWindow", "Calibration Curve Interpolation ", None, QtGui.QApplication.UnicodeUTF8))
        self.calb_int.setCheckable(False)
        self.calb_int.setObjectName(_fromUtf8("calb_int"))
        self.cubic = QtGui.QRadioButton(self.calb_int)
        self.cubic.setGeometry(QtCore.QRect(20, 15, 151, 17))
        self.cubic.setText(QtGui.QApplication.translate("MainWindow", "Cubic Spline", None, QtGui.QApplication.UnicodeUTF8))
        self.cubic.setChecked(False)
        self.cubic.setObjectName(_fromUtf8("cubic"))
        self.regGroup = QtGui.QButtonGroup(MainWindow)
        self.regGroup.setObjectName(_fromUtf8("regGroup"))
        self.regGroup.addButton(self.cubic)
        self.linear = QtGui.QRadioButton(self.calb_int)
        self.linear.setGeometry(QtCore.QRect(20, 35, 171, 17))
        self.linear.setText(QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.linear.setChecked(True)
        self.linear.setObjectName(_fromUtf8("linear"))
        self.regGroup.addButton(self.linear)
        
        self.coord = QtGui.QGroupBox(self.centralwidget)
        self.coord.setGeometry(QtCore.QRect(178, 90, 183, 56))
        self.coord.setTitle(QtGui.QApplication.translate("MainWindow", "Original coordinate system", None, QtGui.QApplication.UnicodeUTF8))
        self.coord.setCheckable(False)
        self.coord.setObjectName(_fromUtf8("coord"))
        self.utm = QtGui.QRadioButton(self.coord)
        self.utm.setGeometry(QtCore.QRect(15, 15, 151, 17))
        self.utm.setText(QtGui.QApplication.translate("MainWindow", "UTM (Z30N)", None, QtGui.QApplication.UnicodeUTF8))
        self.utm.setChecked(True)
        self.utm.setObjectName(_fromUtf8("UTM"))
        self.coordGroup = QtGui.QButtonGroup(MainWindow)
        self.coordGroup.setObjectName(_fromUtf8("coordGroup"))
        self.coordGroup.addButton(self.utm)
        self.WGS84 = QtGui.QRadioButton(self.coord)
        self.WGS84.setGeometry(QtCore.QRect(15, 35, 171, 17))
        self.WGS84.setText(QtGui.QApplication.translate("MainWindow", "WGS84 (Raw GF)", None, QtGui.QApplication.UnicodeUTF8))
        self.WGS84.setChecked(False)
        self.WGS84.setObjectName(_fromUtf8("WGS84"))
        self.coordGroup.addButton(self.WGS84)       
        self.os = QtGui.QRadioButton(self.coord)
        self.os.setGeometry(QtCore.QRect(130, 15, 151, 17))
        self.os.setText(QtGui.QApplication.translate("MainWindow", "OS", None, QtGui.QApplication.UnicodeUTF8))
        self.os.setChecked(False)
        self.os.setObjectName(_fromUtf8("OS"))
        self.coordGroup.addButton(self.os)
        self.coordGroup.checkedId()
            
             
        self.process = QtGui.QGroupBox(self.centralwidget)
        self.process.setGeometry(QtCore.QRect(10, 150, 350, 56))
        self.process.setTitle(QtGui.QApplication.translate("MainWindow", "Data processing", None, QtGui.QApplication.UnicodeUTF8))
        self.process.setCheckable(False)
        self.process.setObjectName(_fromUtf8("process"))
        self.despike = QtGui.QCheckBox(self.process)
        self.despike.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.despike.setText(QtGui.QApplication.translate("MainWindow", "Despike", None, QtGui.QApplication.UnicodeUTF8))
        self.despike.setChecked(True)
        self.despike.setTristate(False)
        self.despike.setObjectName(_fromUtf8("despike"))      
        self.data_match = QtGui.QCheckBox(self.process)
        self.data_match.setGeometry(QtCore.QRect(20, 33, 175, 21))
        self.data_match.setText(QtGui.QApplication.translate("MainWindow", "Zero mean raw data?", None, QtGui.QApplication.UnicodeUTF8))
        self.data_match.setChecked(False)
        self.data_match.setTristate(False)
        self.data_match.setObjectName(_fromUtf8("despike"))    
        self.buff = QtGui.QLineEdit(self.process)
        self.buff.setText("1")
        self.buff.setGeometry(QtCore.QRect(310, 11, 30, 20))
        self.buff.setObjectName(_fromUtf8("buff"))   
        self.buff_label = QtGui.QLabel(self.process)
        self.buff_label.setGeometry(QtCore.QRect(180, 13, 126, 20))
        self.buff_label.setText(QtGui.QApplication.translate("MainWindow", "Calibration buffer size (m):", None, QtGui.QApplication.UnicodeUTF8))
        
        self.output = QtGui.QGroupBox(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 210, 350, 56))
        self.output.setTitle(QtGui.QApplication.translate("MainWindow", "Output options", None, QtGui.QApplication.UnicodeUTF8))
        self.output.setCheckable(False)
        self.output.setObjectName(_fromUtf8("output"))
        self.shape = QtGui.QCheckBox(self.output)
        self.shape.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.shape.setText(QtGui.QApplication.translate("MainWindow", "Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.shape.setChecked(True)
        self.shape.setTristate(False)
        self.shape.setObjectName(_fromUtf8("shape"))      
        self.gisgrd = QtGui.QCheckBox(self.output)
        self.gisgrd.setGeometry(QtCore.QRect(20, 33, 81, 21))
        self.gisgrd.setText(QtGui.QApplication.translate("MainWindow", "ArcGIS grids", None, QtGui.QApplication.UnicodeUTF8))
        self.gisgrd.setChecked(True)
        self.gisgrd.setTristate(False)
        self.gisgrd.setObjectName(_fromUtf8("gisgrd"))    
        self.surf = QtGui.QCheckBox(self.output)
        self.surf.setGeometry(QtCore.QRect(150, 13, 81, 21))
        self.surf.setText(QtGui.QApplication.translate("MainWindow", "Surfer grids", None, QtGui.QApplication.UnicodeUTF8))
        self.surf.setChecked(True)
        self.surf.setTristate(False)
        self.surf.setObjectName(_fromUtf8("surf"))  
        self.geopng = QtGui.QCheckBox(self.output)
        self.geopng.setGeometry(QtCore.QRect(150, 33, 81, 21))
        self.geopng.setText(QtGui.QApplication.translate("MainWindow", "Geo PNGs", None, QtGui.QApplication.UnicodeUTF8))
        self.geopng.setChecked(True)
        self.geopng.setTristate(False)
        self.geopng.setObjectName(_fromUtf8("geopng"))         
        self.topo = QtGui.QCheckBox(self.output)
        self.topo.setGeometry(QtCore.QRect(270, 13, 81, 21))
        self.topo.setText(QtGui.QApplication.translate("MainWindow", "Topo grids", None, QtGui.QApplication.UnicodeUTF8))
        self.topo.setChecked(True)
        self.topo.setTristate(False)
        self.topo.setObjectName(_fromUtf8("topo"))        
        
        self.gridding = QtGui.QGroupBox(self.centralwidget)
        self.gridding.setGeometry(QtCore.QRect(10, 270, 350, 90))
        self.gridding.setTitle(QtGui.QApplication.translate("MainWindow", "Set gridding parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.gridding.setCheckable(False)
        self.gridding.setObjectName(_fromUtf8("gridding"))
        self.x_var = QtGui.QLineEdit(self.gridding)
        self.x_var.setText("0.25")
        self.x_var.setGeometry(QtCore.QRect(113, 15, 30, 20))
        self.x_var.setObjectName(_fromUtf8("xinput")) 
        self.x_label = QtGui.QLabel(self.gridding)
        self.x_label.setGeometry(QtCore.QRect(12, 15, 100, 20))
        self.x_label.setText(QtGui.QApplication.translate("MainWindow", "Enter X Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.y_var = QtGui.QLineEdit(self.gridding)
        self.y_var.setText("0.5")
        self.y_var.setGeometry(QtCore.QRect(295, 15, 30, 20))
        self.y_var.setObjectName(_fromUtf8("xinput"))   
        self.y_label = QtGui.QLabel(self.gridding)
        self.y_label.setGeometry(QtCore.QRect(195, 15, 100, 20))
        self.y_label.setText(QtGui.QApplication.translate("MainWindow", "Enter Y Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.arcgrdval = QtGui.QLineEdit(self.gridding)
        self.arcgrdval.setText("0.5")
        self.arcgrdval.setGeometry(QtCore.QRect(195, 38, 30, 20))
        self.arcgrdval.setObjectName(_fromUtf8("xinput"))   
        self.arc_label = QtGui.QLabel(self.gridding)
        self.arc_label.setGeometry(QtCore.QRect(12, 38, 180, 20))
        self.arc_label.setText(QtGui.QApplication.translate("MainWindow", "Enter grid size for ArcGIS export (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.blank = QtGui.QLineEdit(self.gridding)
        self.blank.setText("1")
        self.blank.setGeometry(QtCore.QRect(113, 61, 30, 20))
        self.blank.setObjectName(_fromUtf8("blank"))   
        self.blank_label = QtGui.QLabel(self.gridding)
        self.blank_label.setGeometry(QtCore.QRect(12, 61, 100, 20))
        self.blank_label.setText(QtGui.QApplication.translate("MainWindow", "Blanking radius (m):", None, QtGui.QApplication.UnicodeUTF8))
        
        self.about_pushButton = QtGui.QPushButton(self.centralwidget)
        self.about_pushButton.setGeometry(QtCore.QRect(12, 365, 81, 31))
        self.about_pushButton.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.about_pushButton.setObjectName(_fromUtf8("about_pushButton"))
        
        self.GO_pushButton = QtGui.QPushButton(self.centralwidget)
        self.GO_pushButton.setGeometry(QtCore.QRect(100, 365, 260, 31))
        self.GO_pushButton.setText(QtGui.QApplication.translate("MainWindow", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.GO_pushButton.setObjectName(_fromUtf8("GO_pushButton")) 
              
        self.termgrp = QtGui.QGroupBox(self.centralwidget)
        self.termgrp.setGeometry(QtCore.QRect(10, 400, 350, 85))
        self.termgrp.setTitle(QtGui.QApplication.translate("MainWindow", "Program progress", None, QtGui.QApplication.UnicodeUTF8))
        self.termgrp.setCheckable(False)
        self.termgrp.setObjectName(_fromUtf8("termgrp"))        
        self.terminal = QtGui.QTextBrowser(self.termgrp)
        self.terminal.setGeometry(QtCore.QRect(10, 15, 330, 60))
        
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(12, 470, 250, 51))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow","© 2014 - ArchaeoPY, University of Bradford", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))  
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 374, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

