# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Sep 28 18:04:02 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        #MainWindow.resize(740, 665)
        MainWindow.setGeometry(30, 50, 740, 655)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CMD GPS Data Display and Calibration", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setWindowIcon(QtGui.QIcon('./includes/icon.PNG')) 
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        
        #Widgets for main calb program
        #Calb group box
        self.cprog = QtGui.QGroupBox(self.centralwidget)
        self.cprog.setGeometry(QtCore.QRect(5, 5, 360, 420))
        self.cprog.setTitle(QtGui.QApplication.translate("MainWindow", "CALIBRATE A FILE", None, QtGui.QApplication.UnicodeUTF8))
        self.cprog.setCheckable(False)
        self.cprog.setObjectName(_fromUtf8("cprog"))
        
        #Get files in
        self.open_data_pushButton = QtGui.QPushButton(self.cprog)
        self.open_data_pushButton.setGeometry(QtCore.QRect(5, 15, 111, 23))
        self.open_data_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the CMD data File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_data_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Data File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_data_pushButton.setObjectName(_fromUtf8("open_data_pushButton"))
        self.data_lineEdit = QtGui.QLineEdit(self.cprog)
        self.data_lineEdit.setGeometry(QtCore.QRect(125, 15, 231, 20))
        self.data_lineEdit.setObjectName(_fromUtf8("data_lineEdit"))
        self.open_calb_pushButton = QtGui.QPushButton(self.cprog)
        self.open_calb_pushButton.setGeometry(QtCore.QRect(5, 45, 111, 23))
        self.open_calb_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the CMD data calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibration File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb_pushButton.setObjectName(_fromUtf8("open_calb_pushButton"))
        self.calb_lineEdit = QtGui.QLineEdit(self.cprog)
        self.calb_lineEdit.setGeometry(QtCore.QRect(125, 45, 231, 20))
        self.calb_lineEdit.setObjectName(_fromUtf8("calb_lineEdit"))   
        self.Output_dir_pushButton = QtGui.QPushButton(self.cprog)
        self.Output_dir_pushButton.setGeometry(QtCore.QRect(5, 75, 111, 23))
        self.Output_dir_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a different output directory if required", None, QtGui.QApplication.UnicodeUTF8))
        self.Output_dir_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.Output_dir_pushButton.setObjectName(_fromUtf8("Output_dir_pushButton"))
        self.output_lineEdit = QtGui.QLineEdit(self.cprog)
        self.output_lineEdit.setGeometry(QtCore.QRect(125, 75, 231, 20))
        self.output_lineEdit.setObjectName(_fromUtf8("output_lineEdit"))
        
        #Set regression type
        self.calb_int = QtGui.QGroupBox(self.cprog)
        self.calb_int.setGeometry(QtCore.QRect(5, 105, 161, 56))
        self.calb_int.setTitle(QtGui.QApplication.translate("MainWindow", "Calibration Curve Interpolation ", None, QtGui.QApplication.UnicodeUTF8))
        self.calb_int.setCheckable(False)
        self.calb_int.setObjectName(_fromUtf8("calb_int"))
        self.cubic = QtGui.QRadioButton(self.calb_int)
        self.cubic.setGeometry(QtCore.QRect(20, 15, 151, 17))
        self.cubic.setText(QtGui.QApplication.translate("MainWindow", "Cubic Spline", None, QtGui.QApplication.UnicodeUTF8))
        self.cubic.setChecked(False)
        self.cubic.setObjectName(_fromUtf8("cubic"))
        self.regGroup = QtGui.QButtonGroup(MainWindow)
        self.regGroup.setObjectName(_fromUtf8("regGroup"))
        self.regGroup.addButton(self.cubic)
        self.linear = QtGui.QRadioButton(self.calb_int)
        self.linear.setGeometry(QtCore.QRect(20, 35, 171, 17))
        self.linear.setText(QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.linear.setChecked(True)
        self.linear.setObjectName(_fromUtf8("linear"))
        self.regGroup.addButton(self.linear)
        
        #Determine coordinate system
        self.coord = QtGui.QGroupBox(self.cprog)
        self.coord.setGeometry(QtCore.QRect(173, 105, 183, 56))
        self.coord.setTitle(QtGui.QApplication.translate("MainWindow", "Original coordinate system", None, QtGui.QApplication.UnicodeUTF8))
        self.coord.setCheckable(False)
        self.coord.setObjectName(_fromUtf8("coord"))
        self.utm = QtGui.QRadioButton(self.coord)
        self.utm.setGeometry(QtCore.QRect(15, 15, 151, 17))
        self.utm.setText(QtGui.QApplication.translate("MainWindow", "UTM (Z30N)", None, QtGui.QApplication.UnicodeUTF8))
        self.utm.setChecked(True)
        self.utm.setObjectName(_fromUtf8("UTM"))
        self.coordGroup = QtGui.QButtonGroup(MainWindow)
        self.coordGroup.setObjectName(_fromUtf8("coordGroup"))
        self.coordGroup.addButton(self.utm)
        self.WGS84 = QtGui.QRadioButton(self.coord)
        self.WGS84.setGeometry(QtCore.QRect(15, 35, 171, 17))
        self.WGS84.setText(QtGui.QApplication.translate("MainWindow", "WGS84 (Raw GF)", None, QtGui.QApplication.UnicodeUTF8))
        self.WGS84.setChecked(False)
        self.WGS84.setObjectName(_fromUtf8("WGS84"))
        self.coordGroup.addButton(self.WGS84)       
        self.os = QtGui.QRadioButton(self.coord)
        self.os.setGeometry(QtCore.QRect(130, 15, 151, 17))
        self.os.setText(QtGui.QApplication.translate("MainWindow", "OS", None, QtGui.QApplication.UnicodeUTF8))
        self.os.setChecked(False)
        self.os.setObjectName(_fromUtf8("OS"))
        self.coordGroup.addButton(self.os)
        self.coordGroup.checkedId()            
        
        #Define any preprocessing
        self.process = QtGui.QGroupBox(self.cprog)
        self.process.setGeometry(QtCore.QRect(5, 165, 350, 56))
        self.process.setTitle(QtGui.QApplication.translate("MainWindow", "Data processing", None, QtGui.QApplication.UnicodeUTF8))
        self.process.setCheckable(False)
        self.process.setObjectName(_fromUtf8("process"))
        self.despike = QtGui.QCheckBox(self.process)
        self.despike.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.despike.setText(QtGui.QApplication.translate("MainWindow", "Despike", None, QtGui.QApplication.UnicodeUTF8))
        self.despike.setChecked(True)
        self.despike.setTristate(False)
        self.despike.setObjectName(_fromUtf8("despike"))      
        self.data_match = QtGui.QCheckBox(self.process)
        self.data_match.setGeometry(QtCore.QRect(20, 33, 175, 21))
        self.data_match.setText(QtGui.QApplication.translate("MainWindow", "Zero mean raw data?", None, QtGui.QApplication.UnicodeUTF8))
        self.data_match.setChecked(False)
        self.data_match.setTristate(False)
        self.data_match.setObjectName(_fromUtf8("despike"))    
        self.buff = QtGui.QLineEdit(self.process)
        self.buff.setText("1")
        self.buff.setGeometry(QtCore.QRect(310, 11, 30, 20))
        self.buff.setObjectName(_fromUtf8("buff"))   
        self.buff_label = QtGui.QLabel(self.process)
        self.buff_label.setGeometry(QtCore.QRect(180, 13, 126, 20))
        self.buff_label.setText(QtGui.QApplication.translate("MainWindow", "Calibration buffer size (m):", None, QtGui.QApplication.UnicodeUTF8))
        
        #Choose output methods
        self.output = QtGui.QGroupBox(self.cprog)
        self.output.setGeometry(QtCore.QRect(5, 225, 350, 56))
        self.output.setTitle(QtGui.QApplication.translate("MainWindow", "Output options", None, QtGui.QApplication.UnicodeUTF8))
        self.output.setCheckable(False)
        self.output.setObjectName(_fromUtf8("output"))
        self.shape = QtGui.QCheckBox(self.output)
        self.shape.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.shape.setText(QtGui.QApplication.translate("MainWindow", "Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.shape.setChecked(True)
        self.shape.setTristate(False)
        self.shape.setObjectName(_fromUtf8("shape"))      
        self.gisgrd = QtGui.QCheckBox(self.output)
        self.gisgrd.setGeometry(QtCore.QRect(20, 33, 81, 21))
        self.gisgrd.setText(QtGui.QApplication.translate("MainWindow", "ArcGIS grids", None, QtGui.QApplication.UnicodeUTF8))
        self.gisgrd.setChecked(True)
        self.gisgrd.setTristate(False)
        self.gisgrd.setObjectName(_fromUtf8("gisgrd"))    
        self.surf = QtGui.QCheckBox(self.output)
        self.surf.setGeometry(QtCore.QRect(150, 13, 81, 21))
        self.surf.setText(QtGui.QApplication.translate("MainWindow", "Surfer grids", None, QtGui.QApplication.UnicodeUTF8))
        self.surf.setChecked(True)
        self.surf.setTristate(False)
        self.surf.setObjectName(_fromUtf8("surf"))  
        self.geopng = QtGui.QCheckBox(self.output)
        self.geopng.setGeometry(QtCore.QRect(150, 33, 81, 21))
        self.geopng.setText(QtGui.QApplication.translate("MainWindow", "Geo PNGs", None, QtGui.QApplication.UnicodeUTF8))
        self.geopng.setChecked(True)
        self.geopng.setTristate(False)
        self.geopng.setObjectName(_fromUtf8("geopng"))         
        self.topo = QtGui.QCheckBox(self.output)
        self.topo.setGeometry(QtCore.QRect(270, 13, 81, 21))
        self.topo.setText(QtGui.QApplication.translate("MainWindow", "Topo grids", None, QtGui.QApplication.UnicodeUTF8))
        self.topo.setChecked(True)
        self.topo.setTristate(False)
        self.topo.setObjectName(_fromUtf8("topo"))        
        
        #Enter gridding values
        self.gridding = QtGui.QGroupBox(self.cprog)
        self.gridding.setGeometry(QtCore.QRect(5, 285, 350, 90))
        self.gridding.setTitle(QtGui.QApplication.translate("MainWindow", "Set gridding parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.gridding.setCheckable(False)
        self.gridding.setObjectName(_fromUtf8("gridding"))
        self.x_var = QtGui.QLineEdit(self.gridding)
        self.x_var.setText("0.25")
        self.x_var.setGeometry(QtCore.QRect(113, 15, 30, 20))
        self.x_var.setObjectName(_fromUtf8("xinput")) 
        self.x_label = QtGui.QLabel(self.gridding)
        self.x_label.setGeometry(QtCore.QRect(12, 15, 100, 20))
        self.x_label.setText(QtGui.QApplication.translate("MainWindow", "Enter X Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.y_var = QtGui.QLineEdit(self.gridding)
        self.y_var.setText("0.5")
        self.y_var.setGeometry(QtCore.QRect(295, 15, 30, 20))
        self.y_var.setObjectName(_fromUtf8("xinput"))   
        self.y_label = QtGui.QLabel(self.gridding)
        self.y_label.setGeometry(QtCore.QRect(195, 15, 100, 20))
        self.y_label.setText(QtGui.QApplication.translate("MainWindow", "Enter Y Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.arcgrdval = QtGui.QLineEdit(self.gridding)
        self.arcgrdval.setText("0.5")
        self.arcgrdval.setGeometry(QtCore.QRect(195, 38, 30, 20))
        self.arcgrdval.setObjectName(_fromUtf8("xinput"))   
        self.arc_label = QtGui.QLabel(self.gridding)
        self.arc_label.setGeometry(QtCore.QRect(12, 38, 180, 20))
        self.arc_label.setText(QtGui.QApplication.translate("MainWindow", "Enter grid size for ArcGIS export (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.blank = QtGui.QLineEdit(self.gridding)
        self.blank.setText("1")
        self.blank.setGeometry(QtCore.QRect(113, 61, 30, 20))
        self.blank.setObjectName(_fromUtf8("blank"))   
        self.blank_label = QtGui.QLabel(self.gridding)
        self.blank_label.setGeometry(QtCore.QRect(12, 61, 100, 20))
        self.blank_label.setText(QtGui.QApplication.translate("MainWindow", "Blanking radius (m):", None, QtGui.QApplication.UnicodeUTF8))

        #The big go button
        self.GO_pushButton = QtGui.QPushButton(self.cprog)
        self.GO_pushButton.setAutoDefault(True)
        self.GO_pushButton.setGeometry(QtCore.QRect(5, 380, 350, 31))
        self.GO_pushButton.setText(QtGui.QApplication.translate("MainWindow", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.GO_pushButton.setObjectName(_fromUtf8("GO_pushButton")) 
        
        #Gubbins with which to only view the raw data
        #View data group box
        self.viewer = QtGui.QGroupBox(self.centralwidget)
        self.viewer.setGeometry(QtCore.QRect(375, 72, 360, 353))
        self.viewer.setTitle(QtGui.QApplication.translate("MainWindow", "VIEW AND SAVE A RAW DATA FILE", None, QtGui.QApplication.UnicodeUTF8))
        self.viewer.setCheckable(False)
        self.viewer.setObjectName(_fromUtf8("viewer"))
        
        #Open files etc
        self.open_view_pushButton = QtGui.QPushButton(self.viewer)
        self.open_view_pushButton.setGeometry(QtCore.QRect(5, 15, 111, 23))
        self.open_view_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select raw data file", None, QtGui.QApplication.UnicodeUTF8))
        self.open_view_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Data File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_view_pushButton.setObjectName(_fromUtf8("open_view_pushButton"))
        self.view_lineEdit = QtGui.QLineEdit(self.viewer)
        self.view_lineEdit.setGeometry(QtCore.QRect(125, 15, 231, 20))
        self.view_lineEdit.setObjectName(_fromUtf8("view_lineEdit"))   
        self.Outputv_dir_pushButton = QtGui.QPushButton(self.viewer)
        self.Outputv_dir_pushButton.setGeometry(QtCore.QRect(5, 45, 111, 23))
        self.Outputv_dir_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a different output directory if required", None, QtGui.QApplication.UnicodeUTF8))
        self.Outputv_dir_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.Outputv_dir_pushButton.setObjectName(_fromUtf8("Outputv_dir_pushButton"))
        self.outputv_lineEdit = QtGui.QLineEdit(self.viewer)
        self.outputv_lineEdit.setGeometry(QtCore.QRect(125, 45, 231, 20))
        self.outputv_lineEdit.setObjectName(_fromUtf8("outputv_lineEdit"))
        
        #Determine coordinate system
        self.vcoord = QtGui.QGroupBox(self.viewer)
        self.vcoord.setGeometry(QtCore.QRect(5, 75, 350, 36))
        self.vcoord.setTitle(QtGui.QApplication.translate("MainWindow", "Original coordinate system", None, QtGui.QApplication.UnicodeUTF8))
        self.vcoord.setCheckable(False)
        self.vcoord.setObjectName(_fromUtf8("vcoord"))
        self.vutm = QtGui.QRadioButton(self.vcoord)
        self.vutm.setGeometry(QtCore.QRect(15, 15, 151, 17))
        self.vutm.setText(QtGui.QApplication.translate("MainWindow", "UTM (Z30N)", None, QtGui.QApplication.UnicodeUTF8))
        self.vutm.setChecked(True)
        self.vutm.setObjectName(_fromUtf8("vutm"))
        self.vcoordGroup = QtGui.QButtonGroup(MainWindow)
        self.vcoordGroup.setObjectName(_fromUtf8("vcoordGroup"))
        self.vcoordGroup.addButton(self.vutm)
        self.vWGS84 = QtGui.QRadioButton(self.vcoord)
        self.vWGS84.setGeometry(QtCore.QRect(130, 15, 171, 17))
        self.vWGS84.setText(QtGui.QApplication.translate("MainWindow", "WGS84 (Raw GF)", None, QtGui.QApplication.UnicodeUTF8))
        self.vWGS84.setChecked(False)
        self.vWGS84.setObjectName(_fromUtf8("vWGS84"))
        self.vcoordGroup.addButton(self.vWGS84)       
        self.vos = QtGui.QRadioButton(self.vcoord)
        self.vos.setGeometry(QtCore.QRect(265, 15, 151, 17))
        self.vos.setText(QtGui.QApplication.translate("MainWindow", "OS", None, QtGui.QApplication.UnicodeUTF8))
        self.vos.setChecked(False)
        self.vos.setObjectName(_fromUtf8("vos"))
        self.vcoordGroup.addButton(self.vos)
        self.vcoordGroup.checkedId()       
        
        #Define any preprocessing
        self.vprocess = QtGui.QGroupBox(self.viewer)
        self.vprocess.setGeometry(QtCore.QRect(5, 115, 350, 40))
        self.vprocess.setTitle(QtGui.QApplication.translate("MainWindow", "Data processing", None, QtGui.QApplication.UnicodeUTF8))
        self.vprocess.setCheckable(False)
        self.vprocess.setObjectName(_fromUtf8("vprocess"))
        self.vdespike = QtGui.QCheckBox(self.vprocess)
        self.vdespike.setGeometry(QtCore.QRect(20, 13, 81, 22))
        self.vdespike.setText(QtGui.QApplication.translate("MainWindow", "Despike", None, QtGui.QApplication.UnicodeUTF8))
        self.vdespike.setChecked(True)
        self.vdespike.setTristate(False)
        self.vdespike.setObjectName(_fromUtf8("despikev"))     
        
        #Choose output methods
        self.voutput = QtGui.QGroupBox(self.viewer)
        self.voutput.setGeometry(QtCore.QRect(5, 159, 350, 57))
        self.voutput.setTitle(QtGui.QApplication.translate("MainWindow", "Output options", None, QtGui.QApplication.UnicodeUTF8))
        self.voutput.setCheckable(False)
        self.voutput.setObjectName(_fromUtf8("voutput"))
        self.vshape = QtGui.QCheckBox(self.voutput)
        self.vshape.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.vshape.setText(QtGui.QApplication.translate("MainWindow", "Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.vshape.setChecked(True)
        self.vshape.setTristate(False)
        self.vshape.setObjectName(_fromUtf8("shapev"))      
        self.vgisgrd = QtGui.QCheckBox(self.voutput)
        self.vgisgrd.setGeometry(QtCore.QRect(20, 33, 81, 21))
        self.vgisgrd.setText(QtGui.QApplication.translate("MainWindow", "ArcGIS grids", None, QtGui.QApplication.UnicodeUTF8))
        self.vgisgrd.setChecked(True)
        self.vgisgrd.setTristate(False)
        self.vgisgrd.setObjectName(_fromUtf8("gisgrdv"))    
        self.vsurf = QtGui.QCheckBox(self.voutput)
        self.vsurf.setGeometry(QtCore.QRect(150, 13, 81, 21))
        self.vsurf.setText(QtGui.QApplication.translate("MainWindow", "Surfer grids", None, QtGui.QApplication.UnicodeUTF8))
        self.vsurf.setChecked(True)
        self.vsurf.setTristate(False)
        self.vsurf.setObjectName(_fromUtf8("surfv"))  
        self.vgeopng = QtGui.QCheckBox(self.voutput)
        self.vgeopng.setGeometry(QtCore.QRect(150, 33, 81, 21))
        self.vgeopng.setText(QtGui.QApplication.translate("MainWindow", "Geo PNGs", None, QtGui.QApplication.UnicodeUTF8))
        self.vgeopng.setChecked(True)
        self.vgeopng.setTristate(False)
        self.vgeopng.setObjectName(_fromUtf8("geopngv"))         
        self.vtopo = QtGui.QCheckBox(self.voutput)
        self.vtopo.setGeometry(QtCore.QRect(270, 13, 81, 21))
        self.vtopo.setText(QtGui.QApplication.translate("MainWindow", "Topo grids", None, QtGui.QApplication.UnicodeUTF8))
        self.vtopo.setChecked(True)
        self.vtopo.setTristate(False)
        self.vtopo.setObjectName(_fromUtf8("topov"))   
        
        #Enter gridding values
        self.vgridding = QtGui.QGroupBox(self.viewer)
        self.vgridding.setGeometry(QtCore.QRect(5, 220, 350, 88))
        self.vgridding.setTitle(QtGui.QApplication.translate("MainWindow", "Set gridding parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.vgridding.setCheckable(False)
        self.vgridding.setObjectName(_fromUtf8("vgridding"))
        self.vx_var = QtGui.QLineEdit(self.vgridding)
        self.vx_var.setText(_fromUtf8("0.25"))
        self.vx_var.setGeometry(QtCore.QRect(113, 15, 30, 20))
        self.vx_var.setObjectName(_fromUtf8("xinputv")) 
        self.vx_label = QtGui.QLabel(self.vgridding)
        self.vx_label.setGeometry(QtCore.QRect(12, 15, 100, 20))
        self.vx_label.setText(QtGui.QApplication.translate("MainWindow", "Enter X Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.vy_var = QtGui.QLineEdit(self.vgridding)
        self.vy_var.setText(_fromUtf8("0.25"))
        self.vy_var.setGeometry(QtCore.QRect(295, 15, 30, 20))
        self.vy_var.setObjectName(_fromUtf8("xinputv")) 
        self.vy_label = QtGui.QLabel(self.vgridding)
        self.vy_label.setGeometry(QtCore.QRect(195, 15, 100, 20))
        self.vy_label.setText(QtGui.QApplication.translate("MainWindow", "Enter Y Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.varcgrdval = QtGui.QLineEdit(self.vgridding)
        self.varcgrdval.setText(_fromUtf8("0.5"))
        self.varcgrdval.setGeometry(QtCore.QRect(195, 38, 30, 20))
        self.varcgrdval.setObjectName(_fromUtf8("arcinputv"))   
        self.varc_label = QtGui.QLabel(self.vgridding)
        self.varc_label.setGeometry(QtCore.QRect(12, 38, 180, 20))
        self.varc_label.setText(QtGui.QApplication.translate("MainWindow", "Enter grid size for ArcGIS export (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.vblank = QtGui.QLineEdit(self.vgridding)
        self.vblank.setText(_fromUtf8("1"))
        self.vblank.setGeometry(QtCore.QRect(113, 61, 30, 20))
        self.vblank.setObjectName(_fromUtf8("blankv"))   
        self.vblank_label = QtGui.QLabel(self.vgridding)
        self.vblank_label.setGeometry(QtCore.QRect(12, 61, 100, 20))
        self.vblank_label.setText(QtGui.QApplication.translate("MainWindow", "Blanking radius (m):", None, QtGui.QApplication.UnicodeUTF8))
        
        #The big view button
        self.View_pushButton = QtGui.QPushButton(self.viewer)
        self.View_pushButton.setAutoDefault(True)
        self.View_pushButton.setGeometry(QtCore.QRect(5, 313, 350, 31))
        self.View_pushButton.setText(_fromUtf8("View"))
        #self.View_pushButton.setText(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.View_pushButton.setObjectName(_fromUtf8("View_pushButton")) 
        
        #Gubbins with which to combine calibrated files
        #Combine calb data
        self.calber = QtGui.QGroupBox(self.centralwidget)
        self.calber.setGeometry(QtCore.QRect(5, 430, 730, 204))
        self.calber.setTitle(_fromUtf8("COMBINE OR VIEW PRE-CALIBRATED DATA SETS"))
        #self.calber.setTitle(QtGui.QApplication.translate("MainWindow", "COMBINE PRE-CALIBRATED DATA SETS", None, QtGui.QApplication.UnicodeUTF8))
        self.calber.setCheckable(False)
        self.calber.setObjectName(_fromUtf8("calber"))
        
        #Open files etc
        self.open_calb1_pushButton = QtGui.QPushButton(self.calber)
        self.open_calb1_pushButton.setGeometry(QtCore.QRect(5, 20, 111, 23))
        self.open_calb1_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select file 1", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb1_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrated File 1", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb1_pushButton.setObjectName(_fromUtf8("open_calb1_pushButton"))
        self.calb1_lineEdit = QtGui.QLineEdit(self.calber)
        self.calb1_lineEdit.setGeometry(QtCore.QRect(125, 20, 231, 20))
        self.calb1_lineEdit.setObjectName(_fromUtf8("calb1_lineEdit"))   
        self.open_calb2_pushButton = QtGui.QPushButton(self.calber)
        self.open_calb2_pushButton.setGeometry(QtCore.QRect(5, 50, 111, 23))
        self.open_calb2_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select file 2", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb2_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrated File 2", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb2_pushButton.setObjectName(_fromUtf8("open_calb2_pushButton"))
        self.calb2_lineEdit = QtGui.QLineEdit(self.calber)
        self.calb2_lineEdit.setText("")
        self.calb2_lineEdit.setGeometry(QtCore.QRect(125, 50, 231, 20))
        self.calb2_lineEdit.setObjectName(_fromUtf8("calb2_lineEdit"))  
        self.open_calb3_pushButton = QtGui.QPushButton(self.calber)
        self.open_calb3_pushButton.setGeometry(QtCore.QRect(5, 80, 111, 23))
        self.open_calb3_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select file 3", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb3_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrated File 3", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb3_pushButton.setObjectName(_fromUtf8("open_calb3_pushButton"))
        self.calb3_lineEdit = QtGui.QLineEdit(self.calber)
        self.calb3_lineEdit.setText("")
        self.calb3_lineEdit.setGeometry(QtCore.QRect(125, 80, 231, 20))
        self.calb3_lineEdit.setObjectName(_fromUtf8("calb3_lineEdit")) 
        self.open_calb4_pushButton = QtGui.QPushButton(self.calber)
        self.open_calb4_pushButton.setGeometry(QtCore.QRect(5, 110, 111, 23))
        self.open_calb4_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select file 4", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb4_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrated File 4", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb4_pushButton.setObjectName(_fromUtf8("open_calb2_pushButton"))
        self.calb4_lineEdit = QtGui.QLineEdit(self.calber)
        self.calb4_lineEdit.setText("")
        self.calb4_lineEdit.setGeometry(QtCore.QRect(125, 110, 231, 20))
        self.calb4_lineEdit.setObjectName(_fromUtf8("calb4_lineEdit"))  
        self.open_calb5_pushButton = QtGui.QPushButton(self.calber)
        self.open_calb5_pushButton.setGeometry(QtCore.QRect(5, 140, 111, 23))
        self.open_calb5_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Select file 5", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb5_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrated File 5", None, QtGui.QApplication.UnicodeUTF8))
        self.open_calb5_pushButton.setObjectName(_fromUtf8("open_calb3_pushButton"))
        self.calb5_lineEdit = QtGui.QLineEdit(self.calber)
        self.calb5_lineEdit.setText("")
        self.calb5_lineEdit.setGeometry(QtCore.QRect(125, 140, 231, 20))
        self.calb5_lineEdit.setObjectName(_fromUtf8("calb5_lineEdit")) 
        self.Outputc_dir_pushButton = QtGui.QPushButton(self.calber)
        self.Outputc_dir_pushButton.setGeometry(QtCore.QRect(5, 170, 111, 23))
        self.Outputc_dir_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose a different output directory if required", None, QtGui.QApplication.UnicodeUTF8))
        self.Outputc_dir_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.Outputc_dir_pushButton.setObjectName(_fromUtf8("Outputc_dir_pushButton"))
        self.Outputc_lineEdit = QtGui.QLineEdit(self.calber)
        self.Outputc_lineEdit.setGeometry(QtCore.QRect(125, 170, 231, 20))
        self.Outputc_lineEdit.setObjectName(_fromUtf8("Outputc_lineEdit"))
         
        #Choose output methods
        self.cOutput = QtGui.QGroupBox(self.calber)
        self.cOutput.setGeometry(QtCore.QRect(375, 10, 350, 57))
        self.cOutput.setTitle(QtGui.QApplication.translate("MainWindow", "Output options", None, QtGui.QApplication.UnicodeUTF8))
        self.cOutput.setCheckable(False)
        self.cOutput.setObjectName(_fromUtf8("coutput"))
        self.cshape = QtGui.QCheckBox(self.cOutput)
        self.cshape.setGeometry(QtCore.QRect(20, 13, 81, 21))
        self.cshape.setText(QtGui.QApplication.translate("MainWindow", "Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.cshape.setChecked(True)
        self.cshape.setTristate(False)
        self.cshape.setObjectName(_fromUtf8("cshape"))      
        self.cgisgrd = QtGui.QCheckBox(self.cOutput)
        self.cgisgrd.setGeometry(QtCore.QRect(20, 33, 81, 21))
        self.cgisgrd.setText(QtGui.QApplication.translate("MainWindow", "ArcGIS grids", None, QtGui.QApplication.UnicodeUTF8))
        self.cgisgrd.setChecked(True)
        self.cgisgrd.setTristate(False)
        self.cgisgrd.setObjectName(_fromUtf8("cgisgrd"))    
        self.csurf = QtGui.QCheckBox(self.cOutput)
        self.csurf.setGeometry(QtCore.QRect(150, 13, 81, 21))
        self.csurf.setText(QtGui.QApplication.translate("MainWindow", "Surfer grids", None, QtGui.QApplication.UnicodeUTF8))
        self.csurf.setChecked(True)
        self.csurf.setTristate(False)
        self.csurf.setObjectName(_fromUtf8("csurf"))  
        self.cgeopng = QtGui.QCheckBox(self.cOutput)
        self.cgeopng.setGeometry(QtCore.QRect(150, 33, 81, 21))
        self.cgeopng.setText(QtGui.QApplication.translate("MainWindow", "Geo PNGs", None, QtGui.QApplication.UnicodeUTF8))
        self.cgeopng.setChecked(True)
        self.cgeopng.setTristate(False)
        self.cgeopng.setObjectName(_fromUtf8("cgeopng"))         
        self.ctopo = QtGui.QCheckBox(self.cOutput)
        self.ctopo.setGeometry(QtCore.QRect(270, 13, 81, 21))
        self.ctopo.setText(QtGui.QApplication.translate("MainWindow", "Topo grids", None, QtGui.QApplication.UnicodeUTF8))
        self.ctopo.setChecked(True)
        self.ctopo.setTristate(False)
        self.ctopo.setObjectName(_fromUtf8("ctopo"))   
        
        #Enter gridding values
        self.cgridding = QtGui.QGroupBox(self.calber)
        self.cgridding.setGeometry(QtCore.QRect(375, 71, 350, 88))
        self.cgridding.setTitle(QtGui.QApplication.translate("MainWindow", "Set gridding parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.cgridding.setCheckable(False)
        self.cgridding.setObjectName(_fromUtf8("cgridding"))
        self.cx_var = QtGui.QLineEdit(self.cgridding)
        self.cx_var.setText(_fromUtf8("0.25"))
        self.cx_var.setGeometry(QtCore.QRect(113, 15, 30, 20))
        self.cx_var.setObjectName(_fromUtf8("cxinput")) 
        self.cx_label = QtGui.QLabel(self.cgridding)
        self.cx_label.setGeometry(QtCore.QRect(12, 15, 100, 20))
        self.cx_label.setText(QtGui.QApplication.translate("MainWindow", "Enter X Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.cy_var = QtGui.QLineEdit(self.cgridding)
        self.cy_var.setText(_fromUtf8("0.25"))
        self.cy_var.setGeometry(QtCore.QRect(295, 15, 30, 20))
        self.cy_var.setObjectName(_fromUtf8("cxinput")) 
        self.cy_label = QtGui.QLabel(self.cgridding)
        self.cy_label.setGeometry(QtCore.QRect(195, 15, 100, 20))
        self.cy_label.setText(QtGui.QApplication.translate("MainWindow", "Enter Y Spacing (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.carcgrdval = QtGui.QLineEdit(self.cgridding)
        self.carcgrdval.setText(_fromUtf8("0.5"))
        self.carcgrdval.setGeometry(QtCore.QRect(195, 38, 30, 20))
        self.carcgrdval.setObjectName(_fromUtf8("carcinput"))   
        self.carc_label = QtGui.QLabel(self.cgridding)
        self.carc_label.setGeometry(QtCore.QRect(12, 38, 180, 20))
        self.carc_label.setText(QtGui.QApplication.translate("MainWindow", "Enter grid size for ArcGIS export (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.cblank = QtGui.QLineEdit(self.cgridding)
        self.cblank.setText(_fromUtf8("1"))
        self.cblank.setGeometry(QtCore.QRect(113, 61, 30, 20))
        self.cblank.setObjectName(_fromUtf8("cblank"))   
        self.cblank_label = QtGui.QLabel(self.cgridding)
        self.cblank_label.setGeometry(QtCore.QRect(12, 61, 100, 20))
        self.cblank_label.setText(QtGui.QApplication.translate("MainWindow", "Blanking radius (m):", None, QtGui.QApplication.UnicodeUTF8))

        #The big combine button
        self.combine_pushButton = QtGui.QPushButton(self.calber)
        self.combine_pushButton.setAutoDefault(True)
        self.combine_pushButton.setGeometry(QtCore.QRect(375, 164, 350, 31))
        self.combine_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Combine", None, QtGui.QApplication.UnicodeUTF8))
        self.combine_pushButton.setObjectName(_fromUtf8("combine_pushButton")) 
        
        #Bottom of window
        '''
        #Progress reporter
        self.termgrp = QtGui.QGroupBox(self.centralwidget)
        self.termgrp.setGeometry(QtCore.QRect(5, 430, 360, 200))
        self.termgrp.setTitle(QtGui.QApplication.translate("MainWindow", "This box is broken so I put an image in instead", None, QtGui.QApplication.UnicodeUTF8))
        self.termgrp.setCheckable(False)
        self.termgrp.setObjectName(_fromUtf8("termgrp"))        
        #self.terminal = QtGui.QTextBrowser(self.termgrp)
        #self.terminal.setText("This box isnae working pal""\n""Av done a durty fudge insteed cos ah cannae cope anymare")
        #self.terminal.setGeometry(QtCore.QRect(10, 15, 340, 175))              
        self.terminal = QtGui.QLabel(self.termgrp)
        self.terminal.setPixmap(QtGui.QPixmap('/Py/includes/icon.PNG'))
        self.terminal.setGeometry(QtCore.QRect(50, 15, 340, 175)) 
        '''
        
        #About button
        self.about_pushButton = QtGui.QPushButton(self.centralwidget)
        self.about_pushButton.setGeometry(QtCore.QRect(375, 35, 360, 25))
        self.about_pushButton.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.about_pushButton.setObjectName(_fromUtf8("about_pushButton"))        
        
        #Uni Bradford label
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(382, 15, 250, 10))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow","© 2014 - ArchaeoPY, University of Bradford", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))  
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 374, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

